### ISSUE TITLE
Import nextstrain-cli docs

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/docs.nextstrain.org#11]
This is a progress-tracking issue for the incorporation of the nextstrain-cli docs into docs.nextstrain.org.

You can currently see this as a RTD subproject at https://docs.nextstrain.org/projects/cli/en/latest/commands/

Some of these pages are to be switched to a top-level TOC (i.e. https://docs.nextstrain.org) as per the gdoc (and similar to #9) but some should remain as a subproject to keep them versioned (i.e. so that one can access the CLI API docs for a given version of the CLI, see #10).

**Comment by eharkins** [comment]
This is done for now. See #17 to make sure submodule and/or subproject is in sync with this project.
