### ISSUE TITLE
drawing phylogentic tree and map using epidemiological data instead of genetic data

### ISSUE THREAD

**Issue by jielab** [nextstrain/docs.nextstrain.org#118]
Hi, The tree and map generated by Nextstrain is really impressive.

I have 1,000 cases, and I know exactly who transmitted to whom at what time and location, using epidemiological investigation data.

Is there a way to using Nextstriain or something similar to draw the tree and map shown as below?

Thanks!
Jie

![image](https://user-images.githubusercontent.com/26947455/178897019-08eb4811-2e97-4ed2-a22c-f89a892b5964.png)

**Comment by tsibley** [comment]
@jielab The short answer is yes (though maybe with a caveat or two). The longer answer is that you'll probably have to construct/provide the transmission tree yourself (e.g. as a Newick file). You'll also need a metadata table of date, location, etc. for each case. The issues in this repository are mostly for bug reports, so for more guidance on how to do this, try [our discussion forum](https://discussion.nextstrain.org) where members of the Nextstrain team and the community alike answer questions and help each other out.
