### ISSUE TITLE
RTD subprojects should have easy way to go back to the main RTD

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/docs.nextstrain.org#12]
Currently when viewing a RTD subproject, e.g. https://docs.nextstrain.org/projects/cli/en/latest/, it is not obvious how to navigate back to the main RTD (https://docs.nextstrain.org/). 

The solution may be to design the horizontal-axis navigation UI we've discussed and implement this via the RTD template. 

Lower priority than #8 #9 #10 #11

**Comment by eharkins** [comment]
https://github.com/readthedocs/readthedocs.org/issues/6584

**Comment by eharkins** [comment]
https://github.com/nextstrain/sphinx-theme/pull/4 achieves this nicely for now (until we can do https://github.com/nextstrain/docs.nextstrain.org/issues/27).
