### ISSUE TITLE
DOC: Add miniconda install scripts to macOS (and maybe Windows) docs

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/docs.nextstrain.org#121]
Let's add short scripts for installing Miniconda on macOS (and if possible Windows) as we do for Linux

>As for a short script to download and run Miniconda, we provide a multi-command example of doing this for Linux (incl. WSL), but not for macOS or Windows:

>![image](https://user-images.githubusercontent.com/79913/180834865-c5b747e0-9fef-4b90-bca1-e7edd62dbe5d.png)

>Not sure why the difference, but possibly because we're suggesting the graphical installers for macOS and Windows. In any case, addressing that is a separate PR in my mind and not one I'm going to do right now.

_Originally posted by @tsibley in https://github.com/nextstrain/docs.nextstrain.org/issues/120#issuecomment-1194364569_

**Comment by j23414** [comment]
There are several installer scripts for Mac (Intel 86 vs Apple M1 chip) listed and linked in this [miniconda table](https://docs.conda.io/en/latest/miniconda.html#latest-miniconda-installer-links). 

For **Mac Intel 86** it can look like:

```
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
bash Miniconda3-latest-MacOSX-x86_64.sh
# follow through installation prompts
rm Miniconda3-latest-MacOSX-x86_64.sh
```

While for **Mac Apple M1 chip** it can look like:

```
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh
bash Miniconda3-latest-MacOSX-arm64.sh
# follow through installation prompts
rm Miniconda3-latest-MacOSX-arm64.sh
```

@corneliusroemer would documenting both on the MacOS be acceptable? Or do you have a sense that most people have moved to the M1 chip on Mac?

The Window's installer scripts mainly pull exe files

```
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86.exe
```

**Comment by j23414** [comment]
We could also make it more general but complicated to read ;)

```
# Pick one OS and ARCH pair
OS=Windows
ARCH=x86_64.exe
ARCH=x86.exe

OS=MacOSX
ARCH=x86_64.sh
ARCH=arm64.sh

wget https://repo.anaconda.com/miniconda/Miniconda3-latest-${OS}-${ARCH}
```

**Comment by tsibley** [comment]
> would documenting both on the MacOS be acceptable? Or do you have a sense that most people have moved to the M1 chip on Mac?

My 2¢ is we'd want to document both. The M1 Macs are still probably at least a couple years from being ubiquitous enough to drop Intel Mac instructions.

**Comment by corneliusroemer** [comment]
Also possible: we could make it autodetect mac architecture

https://stackoverflow.com/questions/65259300/detect-apple-silicon-from-command-line

We should offer both - as long as there's >10% usage of Intel out there. And Macs last quite long so it'll be some time.

**Comment by victorlin** [comment]
My opinion is to suggest Intel install for all Macs, with a note that non-emulated M1 install is also an option but be aware of the limitations. With the current state of things, installing M1 for the average bioinformatics researcher will likely cause environment headaches and you'd need to emulate many popular packages anyways. For example, our current steps create the `nextstrain` environment under emulation which is comparable to creating it with Intel-installed miniconda. More: https://github.com/nextstrain/docs.nextstrain.org/issues/109#issuecomment-1192006688

**Comment by corneliusroemer** [comment]
I'm just installing things fresh on my new M1 Pro - so will document the journey and what I notice here:

1. We may want to recommend installing `mambaforge` for those who don't have conda yet - it comes preconfigured for conda-forge and with mamba preinstalled. Sensible defaults.
This is a general point that we could use for all installations.
Mac specific: It's installable via brew (many will have brew): `brew install --cask mambaforge`
Alternatively: script is available here for all platforms https://github.com/conda-forge/miniforge#unix-like-platforms

2. I would appreciate a quick explanation why it's necessary to create an ox64 base environment and use that. Is that still applicable? Would be nice to have a quick link to the issue where we discussed this for the interested reader. Because I'd expect conda to be able to deal with the right channels automatically.
Specifically I mean this part
>If using a newer Mac with an [Apple silicon chip](https://support.apple.com/en-us/HT211814) (e.g. M1), first run these commands to ensure Conda creates the environment with osx-64 emulation:
```
# Create a new environment using Intel packages called base_osx-64
CONDA_SUBDIR=osx-64 conda create -n base_osx-64 python

# Activate new Intel-based environment
conda activate base_osx-64

# Ensure future Conda commands in this environment use Intel packages too.
conda config --env --set subdir osx-64
```

3. Mac uses `zsh` by default - and the way it's shipped `#` is not a valid comment start character in zsh, not a huge problem but not ideal to show errors during interactive install with copy/paste
```zsh
(base) corneliusromer@Corneliuss-MacBook-Pro ~ % # Create a new environment using Intel packages called base_osx-64
CONDA_SUBDIR=osx-64 mamba create -n base_osx-64 python

# Activate new Intel-based environment
conda activate base_osx-64

# Ensure future Conda commands in this environment use Intel packages too.
conda config --env --set subdir osx-64
zsh: command not found: #
```
See: https://apple.stackexchange.com/questions/405246/zsh-comment-character

4. Also, danger: the `;` in a (non-)comment means next work starts a command. So don't execute this in zsh, it looks harmless but boom.
```zsh
#! zsh
# This is not a comment on Mac default zsh
# But Mac zsh will just error here and not do anything - well unless # is a command itself
# But this is dangerous
# This looks still like a comment; but this here will be executed after ;
# So this will remove all files; rm -rf /
# And oh it looks so innocent in this harmless codeblock
echo "Hello World"
```

**Comment by victorlin** [comment]
> @corneliusroemer: I would appreciate a quick explanation why it's necessary to create an ox64 base environment and use that. Is that still applicable?

See #124 for the newer suggestion and detailed reasoning in a new FAQ page.

**Comment by victorlin** [comment]
Closing this issue since we no longer provide explicit instructions for setting up Conda environments for an ambient runtime. The managed Conda runtime (this issue predates its existence) takes care of the installation under the hood.
