### ISSUE TITLE
Add instructions for users who have already installed Conda

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/docs.nextstrain.org#125]
In https://github.com/nextstrain/docs.nextstrain.org/pull/124 you seem to have removed the snippets for how to set an Intel emulation environment.

Talking about this snippet:
https://github.com/nextstrain/docs.nextstrain.org/blob/877dbaac5362fa60aff8426cc49962f0b6009888/src/install.rst#L86-L100

This is sad. I've already got the ARM miniconda installed. What do I do now?

I don't think everyone will want to uninstall conda just to install the Nextstrain environment.

We should definitely allow both options. If you set up fresh: it's easiest to use Intel miniconda.

If you've already got conda, this is how you enable Intel emulation environment.

@tsibley @victorlin

**Comment by corneliusroemer** [comment]
Actually, I just tried using the base_osx-64 environment and it didn't work.

What seems to work instead is to add the following after creation of the environment but before doing the installation:
```
conda config --env --set subdir osx-64
```

That's also much easier, just need to add another config variable - to the 4 we have already.

**Comment by victorlin** [comment]
@corneliusroemer that's the current recommendation, it's just a bit more hidden now:

https://github.com/nextstrain/docs.nextstrain.org/blob/5b5f71fcfa65463c3920cfbdd340814d2be9e5d9/src/reference/faq.rst?plain=1#L23-L29

**Comment by victorlin** [comment]
> @corneliusroemer: I've already got the ARM miniconda installed.

The main point of #124 is to recommend the average user to not do this. I'd assume the link in note is clear enough for power users like yourself:

![image](https://user-images.githubusercontent.com/13424970/183480173-5c8f982a-b9bf-4073-824a-d31c27efe703.png)

Let me know how it could be more clear. Mainly I want to offload these alternative installation paths to the new FAQ page, to avoid confusion for the average user.

**Comment by corneliusroemer** [comment]
Hmm, but the point here is that the average user may already have installed conda

We need to give them an option, too.

That's why I think we need to at least explicitly mention where one can find information on what to do if one has conda installed already.

Am I missing something?

**Comment by corneliusroemer** [comment]
Also I noticed that the thing with base_osx-arm didn't work. I had to add the variable to the new environment, it didn't get inherited.

**Comment by victorlin** [comment]
> That's why I think we need to at least explicitly mention where one can find information on what to do if one has conda installed already.

I see, that's valid. The install docs haven't taken this scenario into account, so I think this is more of an https://github.com/nextstrain/docs.nextstrain.org/labels/enhancement than https://github.com/nextstrain/docs.nextstrain.org/labels/bug.

**Comment by victorlin** [comment]
> Also I noticed that the thing with base_osx-arm didn't work. I had to add the variable to the new environment, it didn't get inherited.

Yeah, that's why I removed the suggestion of intermediate environment. The `subdir=osx-64` config is only valid for conda commands run in the environment it's set in. In the old docs, this meant having it set on the intermediate environment would allow `mamba create ... augur ...` to install using `osx-64`. But once the new environment is activated, you would still need to set `subdir=osx-64` there which we didn't include a recommendation for.
