### ISSUE TITLE
Make installation path for Apple silicon users less complicated

### ISSUE THREAD

**Issue by victorlin** [nextstrain/docs.nextstrain.org#127]
### Context

Currently,

1. We recommend "Native" runtime for Apple silicon users because [emulated Docker is slow](https://github.com/nextstrain/docker-base/issues/35#issuecomment-1059480588).
2. Conda installation on Apple silicon has many quirks, and requires users that already have Conda installed to [read through a lengthy FAQ page](https://github.com/nextstrain/docs.nextstrain.org/pull/126).

As people start using newer Macs, we will see more users being caught in this complicated installation path.

### Possible solutions

1. Wait until a full Nextstrain installation on `arm64` Conda is possible. This means all of the following which currently don't support `arm64`/`noarch` must add support for that:

    1. Augur dependencies
    2. Auspice
    3. Other packages we include in the current installation, [mostly to support running the ncov workflow](https://github.com/nextstrain/docs.nextstrain.org/pull/115).

    This could be achieved if [bioconda adds support for compiling recipes on `arm64`](https://github.com/bioconda/bioconda-recipes/issues/23454), which is something @corneliusroemer [brought up in Slack](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1659967967445329), but timeline is pretty much out of our hands here.

2. Provide a new "Conda" runtime which gets set up and updated independently from any existing installation. This was @tsibley's idea mentioned during our installation discussion meeting. This would use the Intel installer for all Macs, [in line with our current recommendation](https://github.com/nextstrain/docs.nextstrain.org/blob/5b5f71fcfa65463c3920cfbdd340814d2be9e5d9/src/reference/faq.rst#why-recommend-the-intel-miniconda-installer-for-mac-computers-with-apple-silicon-eg-m1). Update: this is happening over at https://github.com/nextstrain/cli/pull/218.

3. Provide "native" Docker support which will hopefully make Docker runtime speeds comparable to current Native runtime speeds on Apple silicon. This would require finishing off https://github.com/nextstrain/docker-base/issues/35 and doing some benchmarking.

**Comment by tsibley** [comment]
2 and 3 are my preferred approaches here. I assume 1 may happen on its own (or become more feasible at least) with enough time.

**Comment by victorlin** [comment]
Both solutions 2 and 3 have been completed, and the installation path is better as of https://github.com/nextstrain/docs.nextstrain.org/pull/157.
