### ISSUE TITLE
Fix links after migrating to read the docs

### ISSUE THREAD

**Issue by eharkins** [nextstrain/docs.nextstrain.org#14]
There are many links which will not work or not make sense after migrating everything to be hosted on the same domain.

Here are some examples:

- Relative paths in documents which are genuinely migrated to this repository (as opposed to those which remain in their own repository and are imported from a submodule), e.g. links to `/docs/*` in nextstrain.org documents.
- "Links out" from one docs domain to another (e.g. https://nextstrain.org/docs/getting-started/local-installation#install-augur-with-python) will no longer make sense; we'll want to change these to internal read the docs paths.
- Relative paths to non-markdown, github hosted files from github hosted docs domains (e.g. on this page https://nextstrain.github.io/ncov/customizing-analysis) will need to be replaced with the full github url so that they work on read the docs.

**Comment by eharkins** [comment]
Hopefully redirects will cover most of this, but there might be some links in nextstrain repo readmes that we will want to change, or at least the language around the links may change, e.g. https://github.com/nextstrain/.github/blob/master/CONTRIBUTING.md#contribute-documentation

**Comment by genehack** [comment]
As `make linkcheck` now runs without error on `docs.nextstrain.org:master`, I am closing this issue.
