### ISSUE TITLE
Add docs for "tiered" subsampling

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/docs.nextstrain.org#187]
A common question we get asked by users is how to do "tiered" subsampling, i.e. they want to use different subsampling parameters for `augur filter` for different geolocations. For example, a local public health department may want to have different subsampling parameters for global, country, neighboring states, and local sequences. 

The docs should aim to explain both the concept of tiered subsampling and provide examples of accomplishing this with Snakemake. 

1. Show how this can be done manually with multiple invocations of `augur filter` that does subsampling + a final invocation of `augur filter` that uses `--exclude-all` and `--include` flags to get the final set of sequences.
2. Show how this can be done in Snakemake with hard-coded invocations of `augur filter` per geolocation.
3. Show how this can be done in Snakemake with the [config-based subsampling approach](https://github.com/NW-PaGe/WNV-nextstrain/pull/1)

**Comment by victorlin** [comment]
This is now live as [Filtering and Subsampling – Nextstrain documentation](https://docs.nextstrain.org/en/latest/guides/bioinformatics/filtering-and-subsampling.html). I chose to skip (2) "show how this can be done in Snakemake with hard-coded invocations of `augur filter` per geolocation" to keep the docs concise. Open to further suggestions.
