### ISSUE TITLE
Update install docs to indicate supported/required Python version

### ISSUE THREAD

**Issue by genehack** [nextstrain/docs.nextstrain.org#201]
There's a [known issue](https://github.com/nextstrain/augur/issues/1334) that getting Nextstrain (specifically, Augur) install requires a particular Python version, due to dependencies having specific supported versions.

Update the "ambient" option install docs to make this more clear.

**Comment by victorlin** [comment]
Context from [Slack thread](https://bedfordlab.slack.com/archives/C0K3GS3J8/p1714421971153279):

> You can `pip install nextstrain-augur` on any Python [≥3.8](https://github.com/nextstrain/augur/blob/bb86f5629ccddb3bbfca858367cf37a4106e8f49/setup.py#L5), but installing through the Bioconda package won't work on Python ≥3.11 ([a known issue](https://github.com/nextstrain/augur/issues/1334)).
