### ISSUE TITLE
how to get Latest clades.tsv for ( augur clades )

### ISSUE THREAD

**Issue by kiranpatil222** [nextstrain/docs.nextstrain.org#208]
Hi,

I am new to nextstrain, following [(tutorial ) ](https://docs.nextstrain.org/en/latest/tutorials/creating-a-phylogenetic-workflow.html#identify-amino-acid-mutations) Phylo tree for our lab 2023 data, i have completed all steps until translate, I was wondering how to add clad/lineage data to phylo tree through

From where can i get `clades.csv` for the latest lineages to view  add/ augur export  auspice in the command below 
```
augur clades \
  --tree results/tree.nwk \
  --mutations results/nt_muts.json results/aa_muts.json \
  --clades config/clades.tsv \
  --output-node-data results/clades.json
```
( Basically i want to see how evolution of lineages /clades over 2023 ( Monthly) in phylo tree, like JN1 / BA/ KP.1.2.3  on for my data)

**Comment by kiranpatil222** [comment]
Hello Team,

There are hundreds of links one leads to other, as i couldn't not find it anywhere which required for my command so i posted here, if you can post me to the link which answers my query that will be helpful,

**Comment by huddlej** [comment]
Hi @kiranpatil222! I'm sorry that you've had to bounce around the various Nextstrain GitHub repositories a bit to get this question answered. If you are working from [the VEME tutorial](https://github.com/blab/veme-2022) which is based on SARS-CoV-2 data, then you can find [the latest Nextstrain clades TSV in the corresponding GitHub repository](https://github.com/nextstrain/ncov/blob/master/defaults/clades.tsv).

Even if you update the clades TSV in that VEME tutorial, the metadata and sequences from that tutorial are still older data. Once you feel comfortable with the logical flow of the steps in the VEME tutorial, you may want to jump to [the SARS-CoV-2-specific tutorials](https://docs.nextstrain.org/projects/ncov/en/latest/index.html) that covers how to run analyses with our Nextstrain workflow with recent data, clade definitions, etc.

**Comment by kiranpatil222** [comment]
@huddlej  Thanks a lot, that should get me going, really appreciate
