### ISSUE TITLE
Read the docs build failures

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/docs.nextstrain.org#209]
Upstream issue: https://github.com/readthedocs/readthedocs.org/issues/11416

## Progress

Repos affected can be found using GitHub search for [`org:nextstrain  python: "mambaforge-22.9"`](https://github.com/search?q=org%3Anextstrain++python%3A+"mambaforge-22.9"&type=code):

- [x] https://github.com/nextstrain/ncov/pull/1122
- [x] https://github.com/nextstrain/auspice/pull/1798
- [x] https://github.com/nextstrain/nextclade/pull/1500
- [x] https://github.com/nextstrain/docs.nextstrain.org/pull/211

## Solutions/workarounds

1. ⏳ Wait for upstream issue to be resolved
2. ⛔️ Use python instead of mambaforge
3. ⛔️ Pin to `sphinx=7.2`
4. ✅ Bump the mambaforge version to 23.11

---

_Initial commentary_

We recently had multiple failures of the Read-the-docs build in Auspice PRs - https://github.com/nextstrain/auspice/pull/1788, https://github.com/nextstrain/auspice/pull/1779. There were no salient changes to docs related code in those PRs (I believe), and in all cases [our action which builds the docs](https://github.com/nextstrain/.github/blob/master/.github/workflows/docs-ci.yaml) succeeded ([example action log](https://github.com/nextstrain/auspice/actions/runs/9541352737/job/26294445176)). Error (full log [here](https://readthedocs.org/projects/nextstrain-auspice/builds/24712428/)):

```console
critical libmamba Pathname can't be converted from UTF-8 to current locale.
Preparing transaction: ...working... done
Verifying transaction: ...working... failed

CondaVerificationError: The package for sphinx located at /home/docs/.asdf/installs/python/mambaforge-22.9.0-3/pkgs/sphinx-7.3.7-py312h5eee18b_0
appears to be corrupted. The path 'bin/sphinx-apidoc'
specified in the package manifest cannot be found.

CondaVerificationError: The package for sphinx located at /home/docs/.asdf/installs/python/mambaforge-22.9.0-3/pkgs/sphinx-7.3.7-py312h5eee18b_0
appears to be corrupted. The path 'bin/sphinx-autogen'
specified in the package manifest cannot be found.

...
```

The same failure occured on the [latest/stable version of Auspice's RTD](https://readthedocs.org/projects/nextstrain-auspice/builds/24712463/)

**Comment by jameshadfield** [comment]
[Nextstrain.org build just completed successfully](https://readthedocs.org/projects/nextstrainorg/builds/24712493/) however this uses python to build not micromamba.

**Comment by tsibley** [comment]
My first question is: What's the current locale for the RTD build system?

Driven by this error:

```
critical libmamba Pathname can't be converted from UTF-8 to current locale.
```

which I think is likely the root cause of all the other errors.

This feels like an RTD build system bug.

**Comment by tsibley** [comment]
https://github.com/readthedocs/readthedocs.org/issues/11416

**Comment by victorlin** [comment]
I think these are the workarounds:

1. Use python instead of mambaforge
2. Pin to `sphinx=7.2`

I think (1) is too big and unnecessary of a change. (2) seems sensible with an inline comment.

**Comment by joverlee521** [comment]
Latest [build of docs in augur](https://readthedocs.org/projects/nextstrain-augur/builds/24837604/) for https://github.com/nextstrain/augur/pull/1493 completed successfully today.

**Comment by victorlin** [comment]
Augur is not affected since, similar to nextstrain.org, it uses Python to build instead of mambaforge.

**Comment by victorlin** [comment]
The upstream issue isn't getting any attention. I'll apply the workaround of pinning `sphinx=7.2` to all affected repos.

**Comment by victorlin** [comment]
I just realized that docs.nextstrain.org is not actually affected as a side effect of the [pin](https://github.com/nextstrain/docs.nextstrain.org/blob/c9246711986094476cdb06af75ad137422b662e1/conda.yml#L10) to `docutils<0.18`, which the broken Sphinx version is not compatible with. It'd still be good to pin `sphinx` separately.

Also, the pin shouldn't be `sphinx=7.2` but a range with an upper cap. I pulled that directly from the upstream issue as a known workaround. Will do some testing to find the earliest version of Sphinx that breaks and cap it to lower than that.

**Comment by victorlin** [comment]
Update❗️I found a better solution: bump the mambaforge version.

I did some searching on the error message and came across https://github.com/conda-forge/python-libarchive-c-feedstock/issues/35#issuecomment-1623133587. This is a known bug in mamba versions <1.4.7. The mambaforge version that we use across affected repos, 22.9, [bundles](https://github.com/conda-forge/miniforge/releases/tag/22.9.0-3) mamba 1.1.0. The next [available](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python) mambaforge version, 23.11, [bundles](https://github.com/conda-forge/miniforge/releases/tag/23.11.0-0) mamba 1.5.5.

**Comment by victorlin** [comment]
All RTD configs using `mambaforge-22.9` have been updated to use `mambaforge-23.11`.
