### ISSUE TITLE
Docs build failed on default branch

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/docs.nextstrain.org#214]
Error from the [CI workflow run](https://github.com/nextstrain/docs.nextstrain.org/actions/runs/9960748534/job/27520703157#step:5:22):

```
Extension error:
Could not import extension sphinxarg.ext (exception: cannot import name 'get_default_settings' from 'docutils.frontend' (/usr/share/miniconda/envs/test/lib/python3.12/site-packages/docutils/frontend.py))
make: *** [Makefile:20: html] Error 2
```

**Comment by joverlee521** [comment]
Blocked on upstream issue https://github.com/sphinx-doc/sphinx-argparse/issues/57. 

Looks like we need to pin `sphinx-argparse<0.5.0` like we did in https://github.com/nextstrain/augur/pull/1543

**Comment by jameshadfield** [comment]
Looking at this situation retrospectively, if we encounter future docs breakages do you think waiting for ~48hours and seeing if it fixes itself would be a good idea? The downside is that the docs are slightly out of date for certain periods, but the upside is less churn on our end.
