### ISSUE TITLE
Certain page titles need to be more specific

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/docs.nextstrain.org#22]
https://docs.nextstrain.org/en/migrate/augur/docs/installation/installation.html and https://docs.nextstrain.org/en/migrate/cli/doc/installation.html both have titles "installation" (should be along the lines of "install augur" and "install the nextstrain CLI", respectively)

**Comment by eharkins** [comment]
> https://docs.nextstrain.org/en/migrate/augur/docs/installation/installation.html and https://docs.nextstrain.org/en/migrate/cli/doc/installation.html 

Done in #28, though there are still some instances of this (#31)

**Comment by victorlin** [comment]
We now have a [main installation page](https://docs.nextstrain.org/page/install.html) on the umbrella project as well as individual installation pages on subprojects (e.g. [Augur](https://docs.nextstrain.org/projects/augur/en/stable/installation/installation.html), [CLI](https://docs.nextstrain.org/projects/cli/en/latest/installation/)).
