### ISSUE TITLE
Reduce duplicate (or near-duplicate) pages

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/docs.nextstrain.org#23]
Here is a list of pages which are almost direct duplicates (or one is superior) which we should prune down. This list is incomplete (I'll keep adding them as I find them).

- [x] https://docs.nextstrain.org/en/migrate/augur/docs/faq/community_hosting.html should be removed / merged into https://docs.nextstrain.org/en/migrate/guides/share/community-builds.html
- [ ] https://docs.nextstrain.org/en/migrate/tutorials/zika.html and https://docs.nextstrain.org/en/migrate/augur/docs/tutorials/zika_tutorial.html
- [x] https://docs.nextstrain.org/en/migrate/learn/what-is-nextstrain/about-nextstrain.html and https://docs.nextstrain.org/en/migrate/learn/what-is-nextstrain/introduction.html

**Comment by eharkins** [comment]
>  https://docs.nextstrain.org/en/migrate/augur/docs/faq/community_hosting.html should be removed / merged into https://docs.nextstrain.org/en/migrate/guides/share/community-builds.html

done in #30 

>  https://docs.nextstrain.org/en/migrate/learn/what-is-nextstrain/about-nextstrain.html and https://docs.nextstrain.org/en/migrate/learn/what-is-nextstrain/introduction.html

done in #29

**Comment by victorlin** [comment]
> https://docs.nextstrain.org/en/migrate/tutorials/zika.html and https://docs.nextstrain.org/en/migrate/augur/docs/tutorials/zika_tutorial.html

These links both 404. I assume the first one refers to the current https://docs.nextstrain.org/en/latest/tutorials/zika.html which now redirects to https://docs.nextstrain.org/en/latest/tutorials/creating-a-phylogenetic-workflow.html. Not sure what the 2nd one would refer to currently, but current Augur docs reference to the first link ([example](https://github.com/nextstrain/augur/blob/6801233ffb1b6ed19ef782a15f8c4e70bd597d4f/docs/faq/what-is-a-build.md?plain=1#L14)) so this looks to be resolved.
