### ISSUE TITLE
Consistent index page table of contents look and feel

### ISSUE THREAD

**Issue by eharkins** [nextstrain/docs.nextstrain.org#34]
@trvrb raised on last week's Nextstrain call that it is a little disorienting (paraphrasing) to have some of the section header pages (AKA "index pages") just show a table of contents, e.g. https://docs.nextstrain.org/en/latest/guides/bioinformatics/index.html, while others have actual content (sometimes in addition to a table of contents), e.g. https://docs.nextstrain.org/en/latest/guides/share/index.html.

I'll leave it to Trevor to suggest the ideal layout for these pages, but one way to improve consistency in terms of displaying content and/or tables of contents would be to just make sure each of these pages have (in this order on the page):

1. At least one sentence (or more in cases where there is a page worth of introductory content like https://docs.nextstrain.org/en/latest/guides/share/index.html) introducing the section
2. Below that, the table of contents.

**Comment by victorlin** [comment]
I inspected current index pages:

```
$ ls -1 **/index.rst
src/guides/bioinformatics/index.rst
src/guides/communicate/index.rst
src/guides/contribute/index.rst
src/guides/share/groups/index.rst
src/guides/share/index.rst
src/index.rst
src/learn/groups/index.rst
src/learn/interpret/index.rst
src/learn/pathogens/index.rst
src/tutorials/creating-a-pathogen-repo/index.rst
src/tutorials/using-a-pathogen-repo/index.rst
```

They all have at least one sentence. All but `src/learn/groups/index.rst` has a table of contents. It's not necessary on that page because there are no other pages under `src/learn/groups/`.
