### ISSUE TITLE
Migrating markdown documents into Read the Docs

### ISSUE THREAD

**Issue by eharkins** [nextstrain/docs.nextstrain.org#4]
When migrating markdown documents from non-Read the Docs domains, some markdown formatted text renders differently Read the Docs project than it does on other platforms. 

For example, tables in markdown documents, e.g. https://nextstrain.github.io/ncov/data-prep, don't render as a table in Read the Docs: https://docs.nextstrain.org/en/migrate-ncov-tutorial/ncov/docs/data-prep.html#required-metadata

When we are moving markdown documents to this repository from other repositories, it seems like this is ok, since we can convert them to restructured text (.rst) if necessary. @huddlej wrote a nice summary of his experience doing that here: https://bedfordlab.slack.com/archives/CSNNWUP71/p1598389705018000

When we are sourcing documents directly from other repositories however (via submodules or otherwise), are there cases where we want to keep them as markdown in their home repos and not have to convert them to .rst?

If so, we might need to figure out a solution to the formatting differences mentioned above.

**Comment by jameshadfield** [comment]
https://github.com/ryanfox/sphinx-markdown-tables seems like it'd do the trick (there are some other solutions but this looks to be the most straightforward). 

Most of our documentation is in (the GitHub variant of) markdown and it'd be nice to keep it this way to (a) allow things like GitHub pages running for that repo and (b) markdown is easier to write (for me at least).

**Comment by eharkins** [comment]
Thanks! This seems to work nicely: https://docs.nextstrain.org/en/migrate-ncov-tutorial/ncov/docs/data-prep.html#required-metadata.

I am closing this and will open more specific issues for other formatting problems related to using markdown documents (from other repositories that we would like to leave as markdown) in read the docs / sphinx.
