### ISSUE TITLE
Decide whether to use nextstrain meta package from Bioconda with pinned versions for installation docs

### ISSUE THREAD

**Issue by huddlej** [nextstrain/docs.nextstrain.org#56]
As described in 4fb61d9 and [this comment on the install docs rewrite PR](https://github.com/nextstrain/docs.nextstrain.org/pull/52#issuecomment-834573018), we need to decide whether to use the `nextstrain` meta package from Bioconda to install all Nextstrain tools or to stick with a manual list of those tools in our docs.

The goal of [the `nextstrain` meta package in Bioconda](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/nextstrain/meta.yaml) was to create a unified starting point for users to install all of the packages from our Nextstrain ecosystem with a simpler install command (e.g., `conda install nextstrain`). We designed this meta package to not pin any specific versions of dependencies, with the hope that the Conda solvers would be able to pull the latest versions of all dependencies as needed.

In practice, however, both Conda's and Mamba's solvers default to installing older versions of Augur even when new versions are available. This specific issue may be caused by [Augur's Bioconda dependency on Snakemake](https://github.com/bioconda/bioconda-recipes/blob/38d9463b096b5789ed33a7dc0293afef8bb2dbe8/recipes/augur/meta.yaml#L31) that [the Augur Python package itself does not have](https://github.com/nextstrain/augur/blob/15dfc8bc5c5a570066ddd5601c9aa82e0c1d2b7d/setup.py#L49-L57) and interactions with Snakemake's other dependencies. Whatever the root cause of the issue, we most likely cannot use the `nextstrain` meta package without pinning specific versions of all dependencies and then updating those manually with separate PRs with each new release of those dependencies.

To avoid this additional maintenance overhead, our current installation docs hardcode the specific list of packages that are included in that meta package as part of the install command. This approach installs the most recent versions of all packages (as expected) and also updates to the latest versions using the simpler `conda update --all` command. However, our suite of Nextstrain tools is likely to change in the future.

The question now is whether we simplify the user's experience by manually pinning versions of Nextstrain tools in the `nextstrain` meta package or we simplify our own development process by hardcoding the list of those tools wherever we provide installation docs (the main docs, seminars, workshops, etc.).

**Comment by victorlin** [comment]
Nextstrain CLI now provides the [Conda runtime](https://docs.nextstrain.org/projects/cli/en/stable/runtimes/conda/) which is based on a package with pinned versions. Users who wish to use their own Conda environment can still do so by setting one up and using it under the ambient runtime.
