### ISSUE TITLE
Dead link 'Edit on Github' on all 'Explore SARS-CoV-2 evolution' subpages

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/docs.nextstrain.org#64]
**Current Behavior**  
All 'Edit on Github' links of 'Explore SARS-CoV-2 evolution' subpages are dead.

**Reproduce**
Click on "Edit on Github" at the top right here: https://github.com/nextstrain/docs.nextstrain.org/blob/master/src/tutorials/SARS-CoV-2/steps/index.md

**Comment by victorlin** [comment]
Not sure what changed, but this seems to be fixed. The current behavior is:

1. Go to https://docs.nextstrain.org/en/latest/index.html
2. Click [Exploring SARS-CoV-2 evolution](https://docs.nextstrain.org/projects/ncov/en/latest/index.html).
    - This is an external link to the [ncov docs project](https://readthedocs.org/projects/ncov/).
3. **Edit on GitHub** link works as expected there.
