### ISSUE TITLE
Clades in Sars-2 tutorial are out of date

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/docs.nextstrain.org#65]
The list of clades is no longer up to date here: https://docs.nextstrain.org/projects/ncov/en/latest/reference/naming_clades.html#current-clades

![image](https://user-images.githubusercontent.com/25161793/125817320-54a623f6-0f94-46ec-b729-0bcb796fbc61.png)

**Comment by victorlin** [comment]
I would vote to remove the table and just leave a link to the tree with clade color-by which is automatically updated.
