### ISSUE TITLE
include non-tutorial documents from the ncov repo

### ISSUE THREAD

**Issue by eharkins** [nextstrain/docs.nextstrain.org#7]
I added any markdown files in the ncov repo (a submodule of this repo) which are not currently a part of this documentation to an "exclude" list [1] so that they don't raise warnings during the build. Some of these may end up being useful documentation outside the context of the ncov repo [2], in which case we would want to remove them from this list and include them in a table of contents specification somewhere in these docs to include them in the build and surface them on the main documentation.

[1] https://github.com/nextstrain/docs.nextstrain.org/blob/9cd873a8f388126084c3bd6df105986528587d0e/src/conf.py#L43-L54
[2] https://github.com/nextstrain/ncov

**Comment by victorlin** [comment]
This is no longer relevant now that ncov docs live in its own subproject: #70

These exclude patterns were removed as part of that PR.
