### ISSUE TITLE
Import auspice docs

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/docs.nextstrain.org#8]
This is a progress-tracker type issue to track the incorporation of auspice documentation into docs.nextstrain.org. The current docs are stored at https://github.com/nextstrain/auspice/tree/master/docs-src/docs, are in markdown format (with YAML frontmatter) and are rendered at https://nextstrain.github.io/auspice. The gdoc contains a mapping of how they shall fit into the new docs TOC structure

**Comment by eharkins** [comment]
If the current state of the augur subproject / submodule set up [1] is to serve as a precedent / template for auspice, we should create a read the docs subproject for auspice, which builds from the documents in the auspice git repo and displays reference material in a distinct RTD domain, presumably `https://docs.nextstrain.org/projects/auspice` - which can be linked in the reference/auspice section of this project.

[1] https://github.com/nextstrain/docs.nextstrain.org/issues/10#issuecomment-702314036

**Comment by jameshadfield** [comment]
> we should create a read the docs subproject for auspice, which builds from the documents in the auspice git repo

#19 achieves this -- @eharkins could you create a RTD domain for auspice using that? (There's still work to be done -- that PR just migrates auspice to RTD, it doesn't modify the contents structure at all)

**Comment by eharkins** [comment]
The bulk of this work is done so I am closing since we have #17 to ensure auspice-repo-stored docs are up to date in this project.
