### ISSUE TITLE
Remove outdated SARS-CoV-2 pages

### ISSUE THREAD

**Issue by tsibley** [nextstrain/docs.nextstrain.org#91]
- [x] Remove all pages under _src/learn/pathogens/coronavirus/_
- [ ] Setup redirects (update _redirects.yml_) for the removed pages to the main Pathogens page? Maybe redirects aren't appropriate since we don't have equivalent information anywhere; the content is truly gone.
- [x] Grep for incoming links to those pages from our other repos to see if anything needs updating
- [x] Update _src/learn/pathogens/index.rst_ to include a broad description and point to https://nextstrain.org/pathogens, https://nextstrain.org/sars-cov-2, and https://nextstrain.org/influenza.

**Comment by tsibley** [comment]
I noticed that basically all of the pages under [Pathogens → SARS-CoV-2](https://docs.nextstrain.org/en/latest/learn/pathogens/coronavirus/) are out of date, last updated at the beginning of the pandemic. Bad, out of date info in this case seems worse than no info.

@trvrb [concurred on Slack](https://bedfordlab.slack.com/archives/C7SDVPBLZ/p1646950877639139?thread_ts=1646944179.090809&cid=C7SDVPBLZ) that we should drop these, and suggested expanding the top-level Pathogens page a bit to link out to our dataset pages on nextstrain.org.

**Comment by tsibley** [comment]
A quick grep with `ghs code -o nextstrain pathogens/coronavirus/` returns [just one result](https://github.com/search?q=user%3Anextstrain+pathogens%2Fcoronavirus%2F&type=code), which is for redirects from nextstrain.org → docs.nextstrain.org that are fine to leave (the pages _did_ move from there).

**Comment by victorlin** [comment]
> Maybe redirects aren't appropriate since we don't have equivalent information anywhere; the content is truly gone.

I agree, though for a user ending up on a 404 page, it's hard to understand where to look for related content (our 404 page is the same as https://readthedocs.org/invalid-page). Maybe this should be a separate issue if not tracked already?

**Comment by tsibley** [comment]
Nod. I think a separate issue, yes. There's [support for custom 404s](https://docs.readthedocs.io/en/stable/hosting.html#custom-not-found-404-pages).
