### ISSUE TITLE
Nextstrain conda installation using mamba doesn't work

### ISSUE THREAD

**Issue by abattenhouse** [nextstrain/docs.nextstrain.org#93]
The description of how to install Nextstrain in a conda using mamba simply does not work. By this I mean that after following the steps, just trying to build the basic example gets an error.

When I have to rebuild my Nextstrain conda from scratch (which sometimes happen when just updating it doesn't work), I use the workflow/envs/nextstrain.yaml file, and also add auspice.

**Comment by victorlin** [comment]
> trying to build the basic example

@abattenhouse does this mean [the Zika example](https://docs.nextstrain.org/en/latest/tutorials/running-a-workflow.html), or the [example in the ncov guide](https://docs.nextstrain.org/projects/ncov/en/latest/analysis/setup.html#run-a-basic-analysis-with-example-data)?

If using ncov, note the [additional installation requirements for Native runtime](https://docs.nextstrain.org/projects/ncov/en/latest/analysis/setup.html#install-nextstrain-components):

```
mamba install -c conda-forge -c bioconda epiweeks nextclade nextalign pangolin pangolearn
```

**Comment by abattenhouse** [comment]
I believe I tried both the ncov basic example, and also the multiple inputs example (which is the type I'm doing).

Wow, I completely didn't look for those extra packages on a different page, especially since before the mamba change was introduced, the previous conda-based instructions included pretty much everything on the page I referenced (although I think I did have to add epiweeks).

I know keeping this all up to date must be challenging, but I'm a pretty sophisticated user, and if I'm struggling, that probably means other are too.

**Comment by victorlin** [comment]
@abattenhouse thanks for clarifying! Previously, though the conda-based instructions worked, it was one of many duplications of our installation documentation which has gotten out of sync.

By linking out to the central installation docs, we solved the problem of duplication, but obviously make it harder on the users to remember to go back to the original page and notice the extra installation steps, which is easy to overlook!

I'll try to come up with a better solution here.
