### ISSUE TITLE
Streamline native installation steps for subproject references

### ISSUE THREAD

**Issue by victorlin** [nextstrain/docs.nextstrain.org#96]
### Context

In the ongoing installation documentation revolution, the initial thought was to de-duplicate installation instructions and have subprojects reference the [central installation guide](https://docs.nextstrain.org/en/latest/install.html).

This has already been done with ncov: [Setup and installation](https://docs.nextstrain.org/projects/ncov/en/latest/analysis/setup.html). However, the new page leads to confusion such as #93. Users are redirected to the central installation docs and follow all the steps there, thinking they are done with installation once finished with that page. They are likely to miss the additional note for native runtime:

<img width="500" alt="ncov-installation-steps" src="https://user-images.githubusercontent.com/13424970/158655396-c309f8af-eb9d-4c03-ada1-8ded19e98e80.png">

### Possible solutions

1. Avoid extra installation steps
    - This is how Docker runtime is handled – it already installs ncov-specific tools that are the reason for additional installation with native runtime.
2. Copy the same installation guide into the project installation page. This would go back to the old model with duplication issues such as getting out of sync.
3. For Snakemake workflows, use the `--use-conda` flag. This would point to the conda environment YAML checked into the workflow-specific repos (e.g. [nextstrain.yaml in ncov](https://github.com/nextstrain/ncov/blob/master/workflow/envs/nextstrain.yaml)).

**Comment by jameshadfield** [comment]
Hmm, I really like the current de-duplication you did @victorlin, and think the screenshot you posted makes things reasonably clear. Have we considered a snakemake warning if the user tries to run the workflow without these packages? (Although to complicate matters, which are needed depends on which rules your workflow uses.)

> This is how Docker runtime is handled

I think there's a consensus that the current approach won't scale to _n_ pathogens, and I know that concepts such as buildpacks have been explored as solutions which result in a per-workflow image. Which is analogous to a workflow having some extra install steps for `--native` 😉

**Comment by victorlin** [comment]
Just had a discussion with @huddlej related to this, and another possible solution would be for Snakemake workflows to guide users to use the `--use-conda` flag. This would point to the conda environment YAML checked into the workflow-specific repos (e.g. [nextstrain.yaml in ncov](https://github.com/nextstrain/ncov/blob/master/workflow/envs/nextstrain.yaml)).

This also helps avoid issues such as https://github.com/bioconda/bioconda-recipes/pull/33757#issuecomment-1072675574 where the current Python version may not yet be supported by workflow-specific packages.
